=== inet-framework/inet/src/inet/mobility/single/TurtleMobility.dtd
<!ELEMENT movements (movement)*>

<!ELEMENT movement (repeat|set|forward|turn|wait|moveto|moveby)*>
<!ATTLIST movement id NMTOKEN #IMPLIED>

<!ELEMENT repeat (repeat|set|forward|turn|wait|moveto|moveby)*>
<!ATTLIST repeat n CDATA #IMPLIED>

<!ELEMENT set EMPTY>
<!ATTLIST set x     CDATA #IMPLIED
              y     CDATA #IMPLIED
              speed CDATA #IMPLIED
              angle CDATA #IMPLIED
              borderPolicy (reflect|wrap|placerandomly|error) #IMPLIED>

<!ELEMENT forward EMPTY>
<!ATTLIST forward d CDATA #IMPLIED
                  t CDATA #IMPLIED>

<!ELEMENT turn EMPTY>
<!ATTLIST turn angle CDATA #REQUIRED>

<!ELEMENT wait EMPTY>
<!ATTLIST wait t CDATA #REQUIRED>

<!ELEMENT moveto EMPTY>
<!ATTLIST moveto x CDATA #IMPLIED
                 y CDATA #IMPLIED
                 t CDATA #IMPLIED>

<!ELEMENT moveby EMPTY>
<!ATTLIST moveby x CDATA #IMPLIED
                 y CDATA #IMPLIED
                 t CDATA #IMPLIED>

=== inet-framework/inet/examples/mobility/turtle.xml
<?xml version="1.0" ?>
<!DOCTYPE movements SYSTEM "../../etc/TurtleMobility.dtd">
<movements>
    <movement id="1">
        <!-- draw a square -->
        <set speed="10" x="100" y="200"/>
        <repeat n="4">
            <forward d="50"/>
            <turn angle="90"/>
        </repeat>
    </movement>

    <movement id="2">
        <!-- two squares, the second 45 degrees tilted -->
        <set x="200" y="200" speed="10" angle="90"/>
        <repeat n="2">
            <repeat n="4">
                <forward d="50"/>
                <turn angle="90"/>
            </repeat>
            <turn angle="45"/>
            <set speed="20"/>
        </repeat>
    </movement>

    <movement id="3">
        <!-- Random Waypoint -->
        <repeat>
            <set speed="uniform(20,60)"/>
            <moveto x="uniform(0,$MAXX)" y="uniform(0,$MAXY)"/>
            <wait t="uniform(0,10)"/>
        </repeat>
    </movement>

    <movement id="4">
        <!-- MassMobility with "reflect" border policy -->
        <repeat>
            <set speed="uniform(10,20)" borderPolicy="reflect"/>
            <turn angle="uniform(-30,30)"/>
            <forward t="uniform(0.1,1)"/>
        </repeat>
    </movement>

    <movement id="5">
        <!-- MassMobility with "wrap" border policy -->
        <repeat>
            <set speed="uniform(10,20)" borderPolicy="wrap"/>
            <turn angle="uniform(-30,30)"/>
            <forward t="uniform(0.1,1)"/>
        </repeat>
    </movement>

    <movement id="6">
        <!-- MassMobility with "placerandomly" border policy -->
        <repeat>
            <set speed="uniform(10,20)" borderPolicy="placerandomly"/>
            <turn angle="uniform(-30,30)"/>
            <forward t="uniform(0.1,1)"/>
        </repeat>
    </movement>

</movements>
